//
//  test.cpp
//  
//
//  Created by Glen Low on 14/08/14.
//
//

#include <iostream>

#include "double_metaphone.h"

const char* tests[][3] =
{
  {"ALLERTON","ALRTN","ALRTN"},
  {"Acton","AKTN","AKTN"},
  {"Adams","ATMS","ATMS"},
  {"Aggar","AKR","AKR"},
  {"Ahl","AL","AL"},
  {"Aiken","AKN","AKN"},
  {"Alan","ALN","ALN"},
  {"Alcock","ALKK","ALKK"},
  {"Alden","ALTN","ALTN"},
  {"Aldham","ALTM","ALTM"},
  {"Allen","ALN","ALN"},
  {"Allerton","ALRTN","ALRTN"},
  {"Alsop","ALSP","ALSP"},
  {"Alwein","ALN","ALN"},
  {"Ambler","AMPLR","AMPLR"},
  {"Andevill","ANTFL","ANTFL"},
  {"Andrews","ANTRS","ANTRS"},
  {"Andreyco","ANTRK","ANTRK"},
  {"Andriesse","ANTRS","ANTRS"},
  {"Angier","ANJ","ANJR"},
  {"Annabel","ANPL","ANPL"},
  {"Anne","AN","AN"},
  {"Anstye","ANST","ANST"},
  {"Appling","APLNK","APLNK"},
  {"Apuke","APK","APK"},
  {"Arnold","ARNLT","ARNLT"},
  {"Ashby","AXP","AXP"},
  {"Astwood","ASTT","ASTT"},
  {"Atkinson","ATKNSN","ATKNSN"},
  {"Audley","ATL","ATL"},
  {"Austin","ASTN","ASTN"},
  {"Avenal","AFNL","AFNL"},
  {"Ayer","AR","AR"},
  {"Ayot","AT","AT"},
  {"Babbitt","PPT","PPT"},
  {"Bachelor","PXLR","PKLR"},
  {"Bachelour","PXLR","PKLR"},
  {"Bailey","PL","PL"},
  {"Baivel","PFL","PFL"},
  {"Baker","PKR","PKR"},
  {"Baldwin","PLTN","PLTN"},
  {"Balsley","PLSL","PLSL"},
  {"Barber","PRPR","PRPR"},
  {"Barker","PRKR","PRKR"},
  {"Barlow","PRL","PRLF"},
  {"Barnard","PRNRT","PRNRT"},
  {"Barnes","PRNS","PRNS"},
  {"Barnsley","PRNSL","PRNSL"},
  {"Barouxis","PRKSS","PRKSS"},
  {"Bartlet","PRTLT","PRTLT"},
  {"Basley","PSL","PSL"},
  {"Basset","PST","PST"},
  {"Bassett","PST","PST"},
  {"Batchlor","PXLR","PXLR"},
  {"Bates","PTS","PTS"},
  {"Batson","PTSN","PTSN"},
  {"Bayes","PS","PS"},
  {"Bayley","PL","PL"},
  {"Beale","PL","PL"},
  {"Beauchamp","PXMP","PKMP"},
  {"Beauclerc","PKLRK","PKLRK"},
  {"Beech","PX","PK"},
  {"Beers","PRS","PRS"},
  {"Beke","PK","PK"},
  {"Belcher","PLXR","PLKR"},
  {"Benjamin","PNJMN","PNJMN"},
  {"Benningham","PNNKM","PNNKM"},
  {"Bereford","PRFRT","PRFRT"},
  {"Bergen","PRJN","PRKN"},
  {"Berkeley","PRKL","PRKL"},
  {"Berry","PR","PR"},
  {"Besse","PS","PS"},
  {"Bessey","PS","PS"},
  {"Bessiles","PSLS","PSLS"},
  {"Bigelow","PJL","PKLF"},
  {"Bigg","PK","PK"},
  {"Bigod","PKT","PKT"},
  {"Billings","PLNKS","PLNKS"},
  {"Bimper","PMPR","PMPR"},
  {"Binker","PNKR","PNKR"},
  {"Birdsill","PRTSL","PRTSL"},
  {"Bishop","PXP","PXP"},
  {"Black","PLK","PLK"},
  {"Blagge","PLK","PLK"},
  {"Blake","PLK","PLK"},
  {"Blanck","PLNK","PLNK"},
  {"Bledsoe","PLTS","PLTS"},
  {"Blennerhasset","PLNRST","PLNRST"},
  {"Blessing","PLSNK","PLSNK"},
  {"Blewett","PLT","PLT"},
  {"Bloctgoed","PLKTKT","PLKTKT"},
  {"Bloetgoet","PLTKT","PLTKT"},
  {"Bloodgood","PLTKT","PLTKT"},
  {"Blossom","PLSM","PLSM"},
  {"Blount","PLNT","PLNT"},
  {"Bodine","PTN","PTN"},
  {"Bodman","PTMN","PTMN"},
  {"BonCoeur","PNKR","PNKR"},
  {"Bond","PNT","PNT"},
  {"Boscawen","PSKN","PSKN"},
  {"Bosworth","PSR0","PSRT"},
  {"Bouchier","PX","PKR"},
  {"Bowne","PN","PN"},
  {"Bradbury","PRTPR","PRTPR"},
  {"Bradder","PRTR","PRTR"},
  {"Bradford","PRTFRT","PRTFRT"},
  {"Bradstreet","PRTSTRT","PRTSTRT"},
  {"Braham","PRHM","PRHM"},
  {"Brailsford","PRLSFRT","PRLSFRT"},
  {"Brainard","PRNRT","PRNRT"},
  {"Brandish","PRNTX","PRNTX"},
  {"Braun","PRN","PRN"},
  {"Brecc","PRK","PRK"},
  {"Brent","PRNT","PRNT"},
  {"Brenton","PRNTN","PRNTN"},
  {"Briggs","PRKS","PRKS"},
  {"Brigham","PRM","PRM"},
  {"Brobst","PRPST","PRPST"},
  {"Brome","PRM","PRM"},
  {"Bronson","PRNSN","PRNSN"},
  {"Brooks","PRKS","PRKS"},
  {"Brouillard","PRLRT","PRLRT"},
  {"Brown","PRN","PRN"},
  {"Browne","PRN","PRN"},
  {"Brownell","PRNL","PRNL"},
  {"Bruley","PRL","PRL"},
  {"Bryant","PRNT","PRNT"},
  {"Brzozowski","PRSSSK","PRTSTSFSK"},
  {"Buide","PT","PT"},
  {"Bulmer","PLMR","PLMR"},
  {"Bunker","PNKR","PNKR"},
  {"Burden","PRTN","PRTN"},
  {"Burge","PRJ","PRK"},
  {"Burgoyne","PRKN","PRKN"},
  {"Burke","PRK","PRK"},
  {"Burnett","PRNT","PRNT"},
  {"Burpee","PRP","PRP"},
  {"Bursley","PRSL","PRSL"},
  {"Burton","PRTN","PRTN"},
  {"Bushnell","PXNL","PXNL"},
  {"Buss","PS","PS"},
  {"Buswell","PSL","PSL"},
  {"Butler","PTLR","PTLR"},
  {"Calkin","KLKN","KLKN"},
  {"Canada","KNT","KNT"},
  {"Canmore","KNMR","KNMR"},
  {"Canney","KN","KN"},
  {"Capet","KPT","KPT"},
  {"Card","KRT","KRT"},
  {"Carman","KRMN","KRMN"},
  {"Carpenter","KRPNTR","KRPNTR"},
  {"Cartwright","KRTRT","KRTRT"},
  {"Casey","KS","KS"},
  {"Catterfield","KTRFLT","KTRFLT"},
  {"Ceeley","SL","SL"},
  {"Chambers","XMPRS","XMPRS"},
  {"Champion","XMPN","XMPN"},
  {"Chapman","XPMN","XPMN"},
  {"Chase","XS","XS"},
  {"Cheney","XN","XN"},
  {"Chetwynd","XTNT","XTNT"},
  {"Chevalier","XFL","XFLR"},
  {"Chillingsworth","XLNKSR0","XLNKSRT"},
  {"Christie","KRST","KRST"},
  {"Chubbuck","XPK","XPK"},
  {"Church","XRX","XRK"},
  {"Clark","KLRK","KLRK"},
  {"Clarke","KLRK","KLRK"},
  {"Cleare","KLR","KLR"},
  {"Clement","KLMNT","KLMNT"},
  {"Clerke","KLRK","KLRK"},
  {"Clibben","KLPN","KLPN"},
  {"Clifford","KLFRT","KLFRT"},
  {"Clivedon","KLFTN","KLFTN"},
  {"Close","KLS","KLS"},
  {"Clothilde","KL0LT","KLTLT"},
  {"Cobb","KP","KP"},
  {"Coburn","KPRN","KPRN"},
  {"Coburne","KPRN","KPRN"},
  {"Cocke","KK","KK"},
  {"Coffin","KFN","KFN"},
  {"Coffyn","KFN","KFN"},
  {"Colborne","KLPRN","KLPRN"},
  {"Colby","KLP","KLP"},
  {"Cole","KL","KL"},
  {"Coleman","KLMN","KLMN"},
  {"Collier","KL","KLR"},
  {"Compton","KMPTN","KMPTN"},
  {"Cone","KN","KN"},
  {"Cook","KK","KK"},
  {"Cooke","KK","KK"},
  {"Cooper","KPR","KPR"},
  {"Copperthwaite","KPR0T","KPRTT"},
  {"Corbet","KRPT","KRPT"},
  {"Corell","KRL","KRL"},
  {"Corey","KR","KR"},
  {"Corlies","KRLS","KRLS"},
  {"Corneliszen","KRNLSN","KRNLXN"},
  {"Cornelius","KRNLS","KRNLS"},
  {"Cornwallis","KRNLS","KRNLS"},
  {"Cosgrove","KSKRF","KSKRF"},
  {"Count of Brionne","KNTFPRN","KNTFPRN"},
  {"Covill","KFL","KFL"},
  {"Cowperthwaite","KPR0T","KPRTT"},
  {"Cowperwaite","KPRT","KPRT"},
  {"Crane","KRN","KRN"},
  {"Creagmile","KRKML","KRKML"},
  {"Crew","KR","KRF"},
  {"Crispin","KRSPN","KRSPN"},
  {"Crocker","KRKR","KRKR"},
  {"Crockett","KRKT","KRKT"},
  {"Crosby","KRSP","KRSP"},
  {"Crump","KRMP","KRMP"},
  {"Cunningham","KNNKM","KNNKM"},
  {"Curtis","KRTS","KRTS"},
  {"Cutha","K0","KT"},
  {"Cutter","KTR","KTR"},
  {"D'Aubigny","TPN","TPKN"},
  {"DAVIS","TFS","TFS"},
  {"Dabinott","TPNT","TPNT"},
  {"Dacre","TKR","TKR"},
  {"Daggett","TKT","TKT"},
  {"Danvers","TNFRS","TNFRS"},
  {"Darcy","TRS","TRS"},
  {"Davis","TFS","TFS"},
  {"Dawn","TN","TN"},
  {"Dawson","TSN","TSN"},
  {"Day","T","T"},
  {"Daye","T","T"},
  {"DeGrenier","TKRN","TKRNR"},
  {"Dean","TN","TN"},
  {"Deekindaugh","TKNT","TKNT"},
  {"Dennis","TNS","TNS"},
  {"Denny","TN","TN"},
  {"Denton","TNTN","TNTN"},
  {"Desborough","TSPRF","TSPRF"},
  {"Despenser","TSPNSR","TSPNSR"},
  {"Deverill","TFRL","TFRL"},
  {"Devine","TFN","TFN"},
  {"Dexter","TKSTR","TKSTR"},
  {"Dillaway","TL","TL"},
  {"Dimmick","TMK","TMK"},
  {"Dinan","TNN","TNN"},
  {"Dix","TKS","TKS"},
  {"Doggett","TKT","TKT"},
  {"Donahue","TNH","TNH"},
  {"Dorfman","TRFMN","TRFMN"},
  {"Dorris","TRS","TRS"},
  {"Dow","T","TF"},
  {"Downey","TN","TN"},
  {"Downing","TNNK","TNNK"},
  {"Dowsett","TST","TST"},
  {"Duck?","TK","TK"},
  {"Dudley","TTL","TTL"},
  {"Duffy","TF","TF"},
  {"Dunn","TN","TN"},
  {"Dunsterville","TNSTRFL","TNSTRFL"},
  {"Durrant","TRNT","TRNT"},
  {"Durrin","TRN","TRN"},
  {"Dustin","TSTN","TSTN"},
  {"Duston","TSTN","TSTN"},
  {"Eames","AMS","AMS"},
  {"Early","ARL","ARL"},
  {"Easty","AST","AST"},
  {"Ebbett","APT","APT"},
  {"Eberbach","APRPK","APRPK"},
  {"Eberhard","APRRT","APRRT"},
  {"Eddy","AT","AT"},
  {"Edenden","ATNTN","ATNTN"},
  {"Edwards","ATRTS","ATRTS"},
  {"Eglinton","AKLNTN","ALNTN"},
  {"Eliot","ALT","ALT"},
  {"Elizabeth","ALSP0","ALSPT"},
  {"Ellis","ALS","ALS"},
  {"Ellison","ALSN","ALSN"},
  {"Ellot","ALT","ALT"},
  {"Elny","ALN","ALN"},
  {"Elsner","ALSNR","ALSNR"},
  {"Emerson","AMRSN","AMRSN"},
  {"Empson","AMPSN","AMPSN"},
  {"Est","AST","AST"},
  {"Estabrook","ASTPRK","ASTPRK"},
  {"Estes","ASTS","ASTS"},
  {"Estey","AST","AST"},
  {"Evans","AFNS","AFNS"},
  {"Fallowell","FLL","FLL"},
  {"Farnsworth","FRNSR0","FRNSRT"},
  {"Feake","FK","FK"},
  {"Feke","FK","FK"},
  {"Fellows","FLS","FLS"},
  {"Fettiplace","FTPLS","FTPLS"},
  {"Finney","FN","FN"},
  {"Fischer","FXR","FSKR"},
  {"Fisher","FXR","FXR"},
  {"Fisk","FSK","FSK"},
  {"Fiske","FSK","FSK"},
  {"Fletcher","FLXR","FLXR"},
  {"Folger","FLKR","FLJR"},
  {"Foliot","FLT","FLT"},
  {"Folyot","FLT","FLT"},
  {"Fones","FNS","FNS"},
  {"Fordham","FRTM","FRTM"},
  {"Forstner","FRSTNR","FRSTNR"},
  {"Fosten","FSTN","FSTN"},
  {"Foster","FSTR","FSTR"},
  {"Foulke","FLK","FLK"},
  {"Fowler","FLR","FLR"},
  {"Foxwell","FKSL","FKSL"},
  {"Fraley","FRL","FRL"},
  {"Franceys","FRNSS","FRNSS"},
  {"Franke","FRNK","FRNK"},
  {"Frascella","FRSL","FRSL"},
  {"Frazer","FRSR","FRSR"},
  {"Fredd","FRT","FRT"},
  {"Freeman","FRMN","FRMN"},
  {"French","FRNX","FRNK"},
  {"Freville","FRFL","FRFL"},
  {"Frey","FR","FR"},
  {"Frick","FRK","FRK"},
  {"Frier","FR","FRR"},
  {"Froe","FR","FR"},
  {"Frorer","FRRR","FRRR"},
  {"Frost","FRST","FRST"},
  {"Frothingham","FR0NKM","FRTNKM"},
  {"Fry","FR","FR"},
  {"Gaffney","KFN","KFN"},
  {"Gage","KJ","KK"},
  {"Gallion","KLN","KLN"},
  {"Gallishan","KLXN","KLXN"},
  {"Gamble","KMPL","KMPL"},
  {"Garbrand","KRPRNT","KRPRNT"},
  {"Gardner","KRTNR","KRTNR"},
  {"Garrett","KRT","KRT"},
  {"Gassner","KSNR","KSNR"},
  {"Gater","KTR","KTR"},
  {"Gaunt","KNT","KNT"},
  {"Gayer","KR","KR"},
  {"Gerken","KRKN","JRKN"},
  {"Gerritsen","KRTSN","JRTSN"},
  {"Gibbs","KPS","JPS"},
  {"Giffard","JFRT","KFRT"},
  {"Gilbert","KLPRT","JLPRT"},
  {"Gill","KL","JL"},
  {"Gilman","KLMN","JLMN"},
  {"Glass","KLS","KLS"},
  {"Goddard","KTRT","KTRT"},
  {"Godfrey","KTFR","KTFR"},
  {"Godwin","KTN","KTN"},
  {"Goodale","KTL","KTL"},
  {"Goodnow","KTN","KTNF"},
  {"Gorham","KRM","KRM"},
  {"Goseline","KSLN","KSLN"},
  {"Gott","KT","KT"},
  {"Gould","KLT","KLT"},
  {"Grafton","KRFTN","KRFTN"},
  {"Grant","KRNT","KRNT"},
  {"Gray","KR","KR"},
  {"Green","KRN","KRN"},
  {"Griffin","KRFN","KRFN"},
  {"Grill","KRL","KRL"},
  {"Grim","KRM","KRM"},
  {"Grisgonelle","KRSKNL","KRSKNL"},
  {"Gross","KRS","KRS"},
  {"Guba","KP","KP"},
  {"Gybbes","KPS","JPS"},
  {"Haburne","HPRN","HPRN"},
  {"Hackburne","HKPRN","HKPRN"},
  {"Haddon?","HTN","HTN"},
  {"Haines","HNS","HNS"},
  {"Hale","HL","HL"},
  {"Hall","HL","HL"},
  {"Hallet","HLT","HLT"},
  {"Hallock","HLK","HLK"},
  {"Halstead","HLSTT","HLSTT"},
  {"Hammond","HMNT","HMNT"},
  {"Hance","HNS","HNS"},
  {"Handy","HNT","HNT"},
  {"Hanson","HNSN","HNSN"},
  {"Harasek","HRSK","HRSK"},
  {"Harcourt","HRKRT","HRKRT"},
  {"Hardy","HRT","HRT"},
  {"Harlock","HRLK","HRLK"},
  {"Harris","HRS","HRS"},
  {"Hartley","HRTL","HRTL"},
  {"Harvey","HRF","HRF"},
  {"Harvie","HRF","HRF"},
  {"Harwood","HRT","HRT"},
  {"Hathaway","H0","HT"},
  {"Haukeness","HKNS","HKNS"},
  {"Hawkes","HKS","HKS"},
  {"Hawkhurst","HKRST","HKRST"},
  {"Hawkins","HKNS","HKNS"},
  {"Hawley","HL","HL"},
  {"Heald","HLT","HLT"},
  {"Helsdon","HLSTN","HLSTN"},
  {"Hemenway","HMN","HMN"},
  {"Hemmenway","HMN","HMN"},
  {"Henck","HNK","HNK"},
  {"Henderson","HNTRSN","HNTRSN"},
  {"Hendricks","HNTRKS","HNTRKS"},
  {"Hersey","HRS","HRS"},
  {"Hewes","HS","HS"},
  {"Heyman","HMN","HMN"},
  {"Hicks","HKS","HKS"},
  {"Hidden","HTN","HTN"},
  {"Higgs","HKS","HKS"},
  {"Hill","HL","HL"},
  {"Hills","HLS","HLS"},
  {"Hinckley","HNKL","HNKL"},
  {"Hipwell","HPL","HPL"},
  {"Hobart","HPRT","HPRT"},
  {"Hoben","HPN","HPN"},
  {"Hoffmann","HFMN","HFMN"},
  {"Hogan","HKN","HKN"},
  {"Holmes","HLMS","HLMS"},
  {"Hoo","H","H"},
  {"Hooker","HKR","HKR"},
  {"Hopcott","HPKT","HPKT"},
  {"Hopkins","HPKNS","HPKNS"},
  {"Hopkinson","HPKNSN","HPKNSN"},
  {"Hornsey","HRNS","HRNS"},
  {"Houckgeest","HKJST","HKKST"},
  {"Hough","H","H"},
  {"Houstin","HSTN","HSTN"},
  {"How","H","HF"},
  {"Howe","H","H"},
  {"Howland","HLNT","HLNT"},
  {"Hubner","HPNR","HPNR"},
  {"Hudnut","HTNT","HTNT"},
  {"Hughes","HS","HS"},
  {"Hull","HL","HL"},
  {"Hulme","HLM","HLM"},
  {"Hume","HM","HM"},
  {"Hundertumark","HNTRTMRK","HNTRTMRK"},
  {"Hundley","HNTL","HNTL"},
  {"Hungerford","HNKRFRT","HNJRFRT"},
  {"Hunt","HNT","HNT"},
  {"Hurst","HRST","HRST"},
  {"Husbands","HSPNTS","HSPNTS"},
  {"Hussey","HS","HS"},
  {"Husted","HSTT","HSTT"},
  {"Hutchins","HXNS","HXNS"},
  {"Hutchinson","HXNSN","HXNSN"},
  {"Huttinger","HTNKR","HTNJR"},
  {"Huybertsen","HPRTSN","HPRTSN"},
  {"Iddenden","ATNTN","ATNTN"},
  {"Ingraham","ANKRHM","ANKRHM"},
  {"Ives","AFS","AFS"},
  {"Jackson","JKSN","AKSN"},
  {"Jacob","JKP","AKP"},
  {"Jans","JNS","ANS"},
  {"Jenkins","JNKNS","ANKNS"},
  {"Jewett","JT","AT"},
  {"Jewitt","JT","AT"},
  {"Johnson","JNSN","ANSN"},
  {"Jones","JNS","ANS"},
  {"Josephine","JSFN","HSFN"},
  {"Judd","JT","AT"},
  {"June","JN","AN"},
  {"Kamarowska","KMRSK","KMRSK"},
  {"Kay","K","K"},
  {"Kelley","KL","KL"},
  {"Kelly","KL","KL"},
  {"Keymber","KMPR","KMPR"},
  {"Keynes","KNS","KNS"},
  {"Kilham","KLM","KLM"},
  {"Kim","KM","KM"},
  {"Kimball","KMPL","KMPL"},
  {"King","KNK","KNK"},
  {"Kinsey","KNS","KNS"},
  {"Kirk","KRK","KRK"},
  {"Kirton","KRTN","KRTN"},
  {"Kistler","KSTLR","KSTLR"},
  {"Kitchen","KXN","KXN"},
  {"Kitson","KTSN","KTSN"},
  {"Klett","KLT","KLT"},
  {"Kline","KLN","KLN"},
  {"Knapp","NP","NP"},
  {"Knight","NT","NT"},
  {"Knote","NT","NT"},
  {"Knott","NT","NT"},
  {"Knox","NKS","NKS"},
  {"Koeller","KLR","KLR"},
  {"La Pointe","LPNT","LPNT"},
  {"LaPlante","LPLNT","LPLNT"},
  {"Laimbeer","LMPR","LMPR"},
  {"Lamb","LMP","LMP"},
  {"Lambertson","LMPRTSN","LMPRTSN"},
  {"Lancto","LNKT","LNKT"},
  {"Landry","LNTR","LNTR"},
  {"Lane","LN","LN"},
  {"Langendyck","LNJNTK","LNKNTK"},
  {"Langer","LNKR","LNJR"},
  {"Langford","LNKFRT","LNKFRT"},
  {"Lantersee","LNTRS","LNTRS"},
  {"Laquer","LKR","LKR"},
  {"Larkin","LRKN","LRKN"},
  {"Latham","LTM","LTM"},
  {"Lathrop","L0RP","LTRP"},
  {"Lauter","LTR","LTR"},
  {"Lawrence","LRNS","LRNS"},
  {"Leach","LX","LK"},
  {"Leager","LKR","LJR"},
  {"Learned","LRNT","LRNT"},
  {"Leavitt","LFT","LFT"},
  {"Lee","L","L"},
  {"Leete","LT","LT"},
  {"Leggett","LKT","LKT"},
  {"Leland","LLNT","LLNT"},
  {"Leonard","LNRT","LNRT"},
  {"Lester","LSTR","LSTR"},
  {"Lestrange","LSTRNJ","LSTRNK"},
  {"Lethem","L0M","LTM"},
  {"Levine","LFN","LFN"},
  {"Lewes","LS","LS"},
  {"Lewis","LS","LS"},
  {"Lincoln","LNKLN","LNKLN"},
  {"Lindsey","LNTS","LNTS"},
  {"Linher","LNR","LNR"},
  {"Lippet","LPT","LPT"},
  {"Lippincott","LPNKT","LPNKT"},
  {"Lockwood","LKT","LKT"},
  {"Loines","LNS","LNS"},
  {"Lombard","LMPRT","LMPRT"},
  {"Long","LNK","LNK"},
  {"Longespee","LNJSP","LNKSP"},
  {"Look","LK","LK"},
  {"Lounsberry","LNSPR","LNSPR"},
  {"Lounsbury","LNSPR","LNSPR"},
  {"Louthe","L0","LT"},
  {"Loveyne","LFN","LFN"},
  {"Lowe","L","L"},
  {"Ludlam","LTLM","LTLM"},
  {"Lumbard","LMPRT","LMPRT"},
  {"Lund","LNT","LNT"},
  {"Luno","LN","LN"},
  {"Lutz","LTS","LTS"},
  {"Lydia","LT","LT"},
  {"Lynne","LN","LN"},
  {"Lyon","LN","LN"},
  {"MacAlpin","MKLPN","MKLPN"},
  {"MacBricc","MKPRK","MKPRK"},
  {"MacCrinan","MKRNN","MKRNN"},
  {"MacKenneth","MKN0","MKNT"},
  {"MacMael nam Bo","MKMLNMP","MKMLNMP"},
  {"MacMurchada","MKMRXT","MKMRKT"},
  {"Macomber","MKMPR","MKMPR"},
  {"Macy","MS","MS"},
  {"Magnus","MNS","MKNS"},
  {"Mahien","MHN","MHN"},
  {"Malmains","MLMNS","MLMNS"},
  {"Malory","MLR","MLR"},
  {"Mancinelli","MNSNL","MNSNL"},
  {"Mancini","MNSN","MNSN"},
  {"Mann","MN","MN"},
  {"Manning","MNNK","MNNK"},
  {"Manter","MNTR","MNTR"},
  {"Marion","MRN","MRN"},
  {"Marley","MRL","MRL"},
  {"Marmion","MRMN","MRMN"},
  {"Marquart","MRKRT","MRKRT"},
  {"Marsh","MRX","MRX"},
  {"Marshal","MRXL","MRXL"},
  {"Marshall","MRXL","MRXL"},
  {"Martel","MRTL","MRTL"},
  {"Martha","MR0","MRT"},
  {"Martin","MRTN","MRTN"},
  {"Marturano","MRTRN","MRTRN"},
  {"Marvin","MRFN","MRFN"},
  {"Mary","MR","MR"},
  {"Mason","MSN","MSN"},
  {"Maxwell","MKSL","MKSL"},
  {"Mayhew","MH","MHF"},
  {"McAllaster","MKLSTR","MKLSTR"},
  {"McAllister","MKLSTR","MKLSTR"},
  {"McConnell","MKNL","MKNL"},
  {"McFarland","MKFRLNT","MKFRLNT"},
  {"McIlroy","MSLR","MSLR"},
  {"McNair","MKNR","MKNR"},
  {"McNair-Landry","MKNRLNTR","MKNRLNTR"},
  {"McRaven","MKRFN","MKRFN"},
  {"Mead","MT","MT"},
  {"Meade","MT","MT"},
  {"Meck","MK","MK"},
  {"Melton","MLTN","MLTN"},
  {"Mendenhall","MNTNL","MNTNL"},
  {"Mering","MRNK","MRNK"},
  {"Merrick","MRK","MRK"},
  {"Merry","MR","MR"},
  {"Mighill","ML","ML"},
  {"Miller","MLR","MLR"},
  {"Milton","MLTN","MLTN"},
  {"Mohun","MHN","MHN"},
  {"Montague","MNTK","MNTK"},
  {"Montboucher","MNTPXR","MNTPKR"},
  {"Moore","MR","MR"},
  {"Morrel","MRL","MRL"},
  {"Morrill","MRL","MRL"},
  {"Morris","MRS","MRS"},
  {"Morton","MRTN","MRTN"},
  {"Moton","MTN","MTN"},
  {"Muir","MR","MR"},
  {"Mulferd","MLFRT","MLFRT"},
  {"Mullins","MLNS","MLNS"},
  {"Mulso","MLS","MLS"},
  {"Munger","MNKR","MNJR"},
  {"Munt","MNT","MNT"},
  {"Murchad","MRXT","MRKT"},
  {"Murdock","MRTK","MRTK"},
  {"Murray","MR","MR"},
  {"Muskett","MSKT","MSKT"},
  {"Myers","MRS","MRS"},
  {"Myrick","MRK","MRK"},
  {"NORRIS","NRS","NRS"},
  {"Nayle","NL","NL"},
  {"Newcomb","NKMP","NKMP"},
  {"Newcomb(e)","NKMP","NKMP"},
  {"Newkirk","NKRK","NKRK"},
  {"Newton","NTN","NTN"},
  {"Niles","NLS","NLS"},
  {"Noble","NPL","NPL"},
  {"Noel","NL","NL"},
  {"Northend","NR0NT","NRTNT"},
  {"Norton","NRTN","NRTN"},
  {"Nutter","NTR","NTR"},
  {"Odding","ATNK","ATNK"},
  {"Odenbaugh","ATNP","ATNP"},
  {"Ogborn","AKPRN","AKPRN"},
  {"Oppenheimer","APNMR","APNMR"},
  {"Otis","ATS","ATS"},
  {"Oviatt","AFT","AFT"},
  {"PRUST?","PRST","PRST"},
  {"Paddock","PTK","PTK"},
  {"Page","PJ","PK"},
  {"Paine","PN","PN"},
  {"Paist","PST","PST"},
  {"Palmer","PLMR","PLMR"},
  {"Park","PRK","PRK"},
  {"Parker","PRKR","PRKR"},
  {"Parkhurst","PRKRST","PRKRST"},
  {"Parrat","PRT","PRT"},
  {"Parsons","PRSNS","PRSNS"},
  {"Partridge","PRTRJ","PRTRJ"},
  {"Pashley","PXL","PXL"},
  {"Pasley","PSL","PSL"},
  {"Patrick","PTRK","PTRK"},
  {"Pattee","PT","PT"},
  {"Patten","PTN","PTN"},
  {"Pawley","PL","PL"},
  {"Payne","PN","PN"},
  {"Peabody","PPT","PPT"},
  {"Peake","PK","PK"},
  {"Pearson","PRSN","PRSN"},
  {"Peat","PT","PT"},
  {"Pedersen","PTRSN","PTRSN"},
  {"Percy","PRS","PRS"},
  {"Perkins","PRKNS","PRKNS"},
  {"Perrine","PRN","PRN"},
  {"Perry","PR","PR"},
  {"Peson","PSN","PSN"},
  {"Peterson","PTRSN","PTRSN"},
  {"Peyton","PTN","PTN"},
  {"Phinney","FN","FN"},
  {"Pickard","PKRT","PKRT"},
  {"Pierce","PRS","PRS"},
  {"Pierrepont","PRPNT","PRPNT"},
  {"Pike","PK","PK"},
  {"Pinkham","PNKM","PNKM"},
  {"Pitman","PTMN","PTMN"},
  {"Pitt","PT","PT"},
  {"Pitts","PTS","PTS"},
  {"Plantagenet","PLNTJNT","PLNTKNT"},
  {"Platt","PLT","PLT"},
  {"Platts","PLTS","PLTS"},
  {"Pleis","PLS","PLS"},
  {"Pleiss","PLS","PLS"},
  {"Plisko","PLSK","PLSK"},
  {"Pliskovitch","PLSKFX","PLSKFX"},
  {"Plum","PLM","PLM"},
  {"Plume","PLM","PLM"},
  {"Poitou","PT","PT"},
  {"Pomeroy","PMR","PMR"},
  {"Poretiers","PRTRS","PRTRS"},
  {"Pote","PT","PT"},
  {"Potter","PTR","PTR"},
  {"Potts","PTS","PTS"},
  {"Powell","PL","PL"},
  {"Pratt","PRT","PRT"},
  {"Presbury","PRSPR","PRSPR"},
  {"Priest","PRST","PRST"},
  {"Prindle","PRNTL","PRNTL"},
  {"Prior","PRR","PRR"},
  {"Profumo","PRFM","PRFM"},
  {"Purdy","PRT","PRT"},
  {"Purefoy","PRF","PRF"},
  {"Pury","PR","PR"},
  {"Quinter","KNTR","KNTR"},
  {"Rachel","RXL","RKL"},
  {"Rand","RNT","RNT"},
  {"Rankin","RNKN","RNKN"},
  {"Ravenscroft","RFNSKFT","RFNSKFT"},
  {"Raynsford","RNSFRT","RNSFRT"},
  {"Reakirt","RKRT","RKRT"},
  {"Reaves","RFS","RFS"},
  {"Reeves","RFS","RFS"},
  {"Reichert","RXRT","RKRT"},
  {"Remmele","RML","RML"},
  {"Reynolds","RNLTS","RNLTS"},
  {"Rhodes","RTS","RTS"},
  {"Richards","RXRTS","RKRTS"},
  {"Richardson","RXRTSN","RKRTSN"},
  {"Ring","RNK","RNK"},
  {"Roberts","RPRTS","RPRTS"},
  {"Robertson","RPRTSN","RPRTSN"},
  {"Robson","RPSN","RPSN"},
  {"Rodie","RT","RT"},
  {"Rody","RT","RT"},
  {"Rogers","RKRS","RJRS"},
  {"Ross","RS","RS"},
  {"Rosslevin","RSLFN","RSLFN"},
  {"Rowland","RLNT","RLNT"},
  {"Ruehl","RL","RL"},
  {"Russell","RSL","RSL"},
  {"Ruth","R0","RT"},
  {"Ryan","RN","RN"},
  {"Rysse","RS","RS"},
  {"Sadler","STLR","STLR"},
  {"Salmon","SLMN","SLMN"},
  {"Salter","SLTR","SLTR"},
  {"Salvatore","SLFTR","SLFTR"},
  {"Sanders","SNTRS","SNTRS"},
  {"Sands","SNTS","SNTS"},
  {"Sanford","SNFRT","SNFRT"},
  {"Sanger","SNKR","SNJR"},
  {"Sargent","SRJNT","SRKNT"},
  {"Saunders","SNTRS","SNTRS"},
  {"Schilling","XLNK","XLNK"},
  {"Schlegel","XLKL","SLKL"},
  {"Scott","SKT","SKT"},
  {"Sears","SRS","SRS"},
  {"Segersall","SJRSL","SKRSL"},
  {"Senecal","SNKL","SNKL"},
  {"Sergeaux","SRJ","SRK"},
  {"Severance","SFRNS","SFRNS"},
  {"Sharp","XRP","XRP"},
  {"Sharpe","XRP","XRP"},
  {"Sharply","XRPL","XRPL"},
  {"Shatswell","XTSL","XTSL"},
  {"Shattack","XTK","XTK"},
  {"Shattock","XTK","XTK"},
  {"Shattuck","XTK","XTK"},
  {"Shaw","X","XF"},
  {"Sheldon","XLTN","XLTN"},
  {"Sherman","XRMN","XRMN"},
  {"Shinn","XN","XN"},
  {"Shirford","XRFRT","XRFRT"},
  {"Shirley","XRL","XRL"},
  {"Shively","XFL","XFL"},
  {"Shoemaker","XMKR","XMKR"},
  {"Short","XRT","XRT"},
  {"Shotwell","XTL","XTL"},
  {"Shute","XT","XT"},
  {"Sibley","SPL","SPL"},
  {"Silver","SLFR","SLFR"},
  {"Simes","SMS","SMS"},
  {"Sinken","SNKN","SNKN"},
  {"Sinn","SN","SN"},
  {"Skelton","SKLTN","SKLTN"},
  {"Skiffe","SKF","SKF"},
  {"Skotkonung","SKTKNNK","SKTKNNK"},
  {"Slade","SLT","XLT"},
  {"Slye","SL","XL"},
  {"Smedley","SMTL","XMTL"},
  {"Smith","SM0","XMT"},
  {"Snow","SN","XNF"},
  {"Soole","SL","SL"},
  {"Soule","SL","SL"},
  {"Southworth","S0R0","STRT"},
  {"Sowles","SLS","SLS"},
  {"Spalding","SPLTNK","SPLTNK"},
  {"Spark","SPRK","SPRK"},
  {"Spencer","SPNSR","SPNSR"},
  {"Sperry","SPR","SPR"},
  {"Spofford","SPFRT","SPFRT"},
  {"Spooner","SPNR","SPNR"},
  {"Sprague","SPRK","SPRK"},
  {"Springer","SPRNKR","SPRNJR"},
  {"St. Clair","STKLR","STKLR"},
  {"St. Claire","STKLR","STKLR"},
  {"St. Leger","STLJR","STLKR"},
  {"St. Omer","STMR","STMR"},
  {"Stafferton","STFRTN","STFRTN"},
  {"Stafford","STFRT","STFRT"},
  {"Stalham","STLM","STLM"},
  {"Stanford","STNFRT","STNFRT"},
  {"Stanton","STNTN","STNTN"},
  {"Star","STR","STR"},
  {"Starbuck","STRPK","STRPK"},
  {"Starkey","STRK","STRK"},
  {"Starkweather","STRK0R","STRKTR"},
  {"Stearns","STRNS","STRNS"},
  {"Stebbins","STPNS","STPNS"},
  {"Steele","STL","STL"},
  {"Stephenson","STFNSN","STFNSN"},
  {"Stevens","STFNS","STFNS"},
  {"Stoddard","STTRT","STTRT"},
  {"Stodder","STTR","STTR"},
  {"Stone","STN","STN"},
  {"Storey","STR","STR"},
  {"Storrada","STRT","STRT"},
  {"Story","STR","STR"},
  {"Stoughton","STFTN","STFTN"},
  {"Stout","STT","STT"},
  {"Stow","ST","STF"},
  {"Strong","STRNK","STRNK"},
  {"Strutt","STRT","STRT"},
  {"Stryker","STRKR","STRKR"},
  {"Stuckeley","STKL","STKL"},
  {"Sturges","STRJS","STRKS"},
  {"Sturgess","STRJS","STRKS"},
  {"Sturgis","STRJS","STRKS"},
  {"Suevain","SFN","SFN"},
  {"Sulyard","SLRT","SLRT"},
  {"Sutton","STN","STN"},
  {"Swain","SN","XN"},
  {"Swayne","SN","XN"},
  {"Swayze","SS","XTS"},
  {"Swift","SFT","XFT"},
  {"Taber","TPR","TPR"},
  {"Talcott","TLKT","TLKT"},
  {"Tarne","TRN","TRN"},
  {"Tatum","TTM","TTM"},
  {"Taverner","TFRNR","TFRNR"},
  {"Taylor","TLR","TLR"},
  {"Tenney","TN","TN"},
  {"Thayer","0R","TR"},
  {"Thember","0MPR","TMPR"},
  {"Thomas","TMS","TMS"},
  {"Thompson","TMPSN","TMPSN"},
  {"Thorne","0RN","TRN"},
  {"Thornycraft","0RNKRFT","TRNKRFT"},
  {"Threlkeld","0RLKLT","TRLKLT"},
  {"Throckmorton","0RKMRTN","TRKMRTN"},
  {"Thwaits","0TS","TTS"},
  {"Tibbetts","TPTS","TPTS"},
  {"Tidd","TT","TT"},
  {"Tierney","TRN","TRN"},
  {"Tilley","TL","TL"},
  {"Tillieres","TLRS","TLRS"},
  {"Tilly","TL","TL"},
  {"Tisdale","TSTL","TSTL"},
  {"Titus","TTS","TTS"},
  {"Tobey","TP","TP"},
  {"Tooker","TKR","TKR"},
  {"Towle","TL","TL"},
  {"Towne","TN","TN"},
  {"Townsend","TNSNT","TNSNT"},
  {"Treadway","TRT","TRT"},
  {"Trelawney","TRLN","TRLN"},
  {"Trinder","TRNTR","TRNTR"},
  {"Tripp","TRP","TRP"},
  {"Trippe","TRP","TRP"},
  {"Trott","TRT","TRT"},
  {"True","TR","TR"},
  {"Trussebut","TRSPT","TRSPT"},
  {"Tucker","TKR","TKR"},
  {"Turgeon","TRJN","TRKN"},
  {"Turner","TRNR","TRNR"},
  {"Tuttle","TTL","TTL"},
  {"Tyler","TLR","TLR"},
  {"Tylle","TL","TL"},
  {"Tyrrel","TRL","TRL"},
  {"Ua Tuathail","AT0L","ATTL"},
  {"Ulrich","ALRX","ALRK"},
  {"Underhill","ANTRL","ANTRL"},
  {"Underwood","ANTRT","ANTRT"},
  {"Unknown","ANKNN","ANKNN"},
  {"Valentine","FLNTN","FLNTN"},
  {"Van Egmond","FNKMNT","FNKMNT"},
  {"Van der Beek","FNTRPK","FNTRPK"},
  {"Vaughan","FKN","FKN"},
  {"Vermenlen","FRMNLN","FRMNLN"},
  {"Vincent","FNSNT","FNSNT"},
  {"Volentine","FLNTN","FLNTN"},
  {"Wagner","AKNR","FKNR"},
  {"Waite","AT","FT"},
  {"Walker","ALKR","FLKR"},
  {"Walter","ALTR","FLTR"},
  {"Wandell","ANTL","FNTL"},
  {"Wandesford","ANTSFRT","FNTSFRT"},
  {"Warbleton","ARPLTN","FRPLTN"},
  {"Ward","ART","FRT"},
  {"Warde","ART","FRT"},
  {"Ware","AR","FR"},
  {"Wareham","ARHM","FRHM"},
  {"Warner","ARNR","FRNR"},
  {"Warren","ARN","FRN"},
  {"Washburne","AXPRN","FXPRN"},
  {"Waterbury","ATRPR","FTRPR"},
  {"Watson","ATSN","FTSN"},
  {"WatsonEllithorpe","ATSNL0RP","FTSNLTRP"},
  {"Watts","ATS","FTS"},
  {"Wayne","AN","FN"},
  {"Webb","AP","FP"},
  {"Weber","APR","FPR"},
  {"Webster","APSTR","FPSTR"},
  {"Weed","AT","FT"},
  {"Weeks","AKS","FKS"},
  {"Wells","ALS","FLS"},
  {"Wenzell","ANSL","FNTSL"},
  {"West","AST","FST"},
  {"Westbury","ASTPR","FSTPR"},
  {"Whatlocke","ATLK","ATLK"},
  {"Wheeler","ALR","ALR"},
  {"Whiston","ASTN","ASTN"},
  {"White","AT","AT"},
  {"Whitman","ATMN","ATMN"},
  {"Whiton","ATN","ATN"},
  {"Whitson","ATSN","ATSN"},
  {"Wickes","AKS","FKS"},
  {"Wilbur","ALPR","FLPR"},
  {"Wilcotes","ALKTS","FLKTS"},
  {"Wilkinson","ALKNSN","FLKNSN"},
  {"Willets","ALTS","FLTS"},
  {"Willett","ALT","FLT"},
  {"Willey","AL","FL"},
  {"Williams","ALMS","FLMS"},
  {"Williston","ALSTN","FLSTN"},
  {"Wilson","ALSN","FLSN"},
  {"Wimes","AMS","FMS"},
  {"Winch","ANX","FNK"},
  {"Winegar","ANKR","FNKR"},
  {"Wing","ANK","FNK"},
  {"Winsley","ANSL","FNSL"},
  {"Winslow","ANSL","FNSLF"},
  {"Winthrop","AN0RP","FNTRP"},
  {"Wise","AS","FS"},
  {"Wood","AT","FT"},
  {"Woodbridge","ATPRJ","FTPRJ"},
  {"Woodward","ATRT","FTRT"},
  {"Wooley","AL","FL"},
  {"Woolley","AL","FL"},
  {"Worth","AR0","FRT"},
  {"Worthen","AR0N","FRTN"},
  {"Worthley","AR0L","FRTL"},
  {"Wright","RT","RT"},
  {"Wyer","AR","FR"},
  {"Wyere","AR","FR"},
  {"Wynkoop","ANKP","FNKP"},
  {"Yarnall","ARNL","ARNL"},
  {"Yeoman","AMN","AMN"},
  {"Yorke","ARK","ARK"},
  {"Young","ANK","ANK"},
  {"ab Wennonwen","APNNN","APNNN"},
  {"ap Llewellyn","APLLN","APLLN"},
  {"ap Lorwerth","APLRR0","APLRRT"},
  {"d'Angouleme","TNKLM","TNKLM"},
  {"de Audeham","TTHM","TTHM"},
  {"de Bavant","TPFNT","TPFNT"},
  {"de Beauchamp","TPXMP","TPKMP"},
  {"de Beaumont","TPMNT","TPMNT"},
  {"de Bolbec","TPLPK","TPLPK"},
  {"de Braiose","TPRS","TPRS"},
  {"de Braose","TPRS","TPRS"},
  {"de Briwere","TPRR","TPRR"},
  {"de Cantelou","TKNTL","TKNTL"},
  {"de Cherelton","TXRLTN","TKRLTN"},
  {"de Cherleton","TXRLTN","TKRLTN"},
  {"de Clare","TKLR","TKLR"},
  {"de Claremont","TKLRMNT","TKLRMNT"},
  {"de Clifford","TKLFRT","TKLFRT"},
  {"de Colville","TKLFL","TKLFL"},
  {"de Courtenay","TKRTN","TKRTN"},
  {"de Fauconberg","TFKNPRK","TFKNPRK"},
  {"de Forest","TFRST","TFRST"},
  {"de Gai","TK","TK"},
  {"de Grey","TKR","TKR"},
  {"de Guernons","TKRNNS","TKRNNS"},
  {"de Haia","T","T"},
  {"de Harcourt","TRKRT","TRKRT"},
  {"de Hastings","TSTNKS","TSTNKS"},
  {"de Hoke","TK","TK"},
  {"de Hooch","TX","TK"},
  {"de Hugelville","TJLFL","TKLFL"},
  {"de Huntingdon","TNTNKTN","TNTNKTN"},
  {"de Insula","TNSL","TNSL"},
  {"de Keynes","TKNS","TKNS"},
  {"de Lacy","TLS","TLS"},
  {"de Lexington","TLKSNKTN","TLKSNKTN"},
  {"de Lusignan","TLSNN","TLSKNN"},
  {"de Manvers","TMNFRS","TMNFRS"},
  {"de Montagu","TMNTK","TMNTK"},
  {"de Montault","TMNTLT","TMNTLT"},
  {"de Montfort","TMNTFRT","TMNTFRT"},
  {"de Mortimer","TMRTMR","TMRTMR"},
  {"de Morville","TMRFL","TMRFL"},
  {"de Morvois","TMRF","TMRFS"},
  {"de Neufmarche","TNFMRX","TNFMRK"},
  {"de Odingsells","TTNKSLS","TTNKSLS"},
  {"de Odyngsells","TTNKSLS","TTNKSLS"},
  {"de Percy","TPRS","TPRS"},
  {"de Pierrepont","TPRPNT","TPRPNT"},
  {"de Plessetis","TPLSTS","TPLSTS"},
  {"de Porhoet","TPRT","TPRT"},
  {"de Prouz","TPRS","TPRS"},
  {"de Quincy","TKNS","TKNS"},
  {"de Ripellis","TRPLS","TRPLS"},
  {"de Ros","TRS","TRS"},
  {"de Salisbury","TSLSPR","TSLSPR"},
  {"de Sanford","TSNFRT","TSNFRT"},
  {"de Somery","TSMR","TSMR"},
  {"de St. Hilary","TSTLR","TSTLR"},
  {"de St. Liz","TSTLS","TSTLS"},
  {"de Sutton","TSTN","TSTN"},
  {"de Toeni","TTN","TTN"},
  {"de Tony","TTN","TTN"},
  {"de Umfreville","TMFRFL","TMFRFL"},
  {"de Valognes","TFLNS","TFLKNS"},
  {"de Vaux","TF","TF"},
  {"de Vere","TFR","TFR"},
  {"de Vermandois","TFRMNT","TFRMNTS"},
  {"de Vernon","TFRNN","TFRNN"},
  {"de Vexin","TFKSN","TFKSN"},
  {"de Vitre","TFTR","TFTR"},
  {"de Wandesford","TNTSFRT","TNTSFRT"},
  {"de Warenne","TRN","TRN"},
  {"de Westbury","TSTPR","TSTPR"},
  {"di Saluzzo","TSLS","TSLTS"},
  {"fitz Alan","FTSLN","FTSLN"},
  {"fitz Geoffrey","FTSJFR","FTSKFR"},
  {"fitz Herbert","FTSRPRT","FTSRPRT"},
  {"fitz John","FTSJN","FTSJN"},
  {"fitz Patrick","FTSPTRK","FTSPTRK"},
  {"fitz Payn","FTSPN","FTSPN"},
  {"fitz Piers","FTSPRS","FTSPRS"},
  {"fitz Randolph","FTSRNTLF","FTSRNTLF"},
  {"fitz Richard","FTSRXRT","FTSRKRT"},
  {"fitz Robert","FTSRPRT","FTSRPRT"},
  {"fitz Roy","FTSR","FTSR"},
  {"fitz Scrob","FTSSKP","FTSSKP"},
  {"fitz Walter","FTSLTR","FTSLTR"},
  {"fitz Warin","FTSRN","FTSRN"},
  {"fitz Williams","FTSLMS","FTSLMS"},
  {"la Zouche","LSX","LSK"},
  {"le Botiller","LPTLR","LPTLR"},
  {"le Despenser","LTSPNSR","LTSPNSR"},
  {"le deSpencer","LTSPNSR","LTSPNSR"},
  {"of Allendale","AFLNTL","AFLNTL"},
  {"of Angouleme","AFNKLM","AFNKLM"},
  {"of Anjou","AFNJ","AFNJ"},
  {"of Aquitaine","AFKTN","AFKTN"},
  {"of Aumale","AFML","AFML"},
  {"of Bavaria","AFPFR","AFPFR"},
  {"of Boulogne","AFPLN","AFPLKN"},
  {"of Brittany","AFPRTN","AFPRTN"},
  {"of Brittary","AFPRTR","AFPRTR"},
  {"of Castile","AFKSTL","AFKSTL"},
  {"of Chester","AFXSTR","AFKSTR"},
  {"of Clermont","AFKLRMNT","AFKLRMNT"},
  {"of Cologne","AFKLN","AFKLKN"},
  {"of Dinan","AFTNN","AFTNN"},
  {"of Dunbar","AFTNPR","AFTNPR"},
  {"of England","AFNKLNT","AFNKLNT"},
  {"of Essex","AFSKS","AFSKS"},
  {"of Falaise","AFFLS","AFFLS"},
  {"of Flanders","AFFLNTRS","AFFLNTRS"},
  {"of Galloway","AFKL","AFKL"},
  {"of Germany","AFKRMN","AFJRMN"},
  {"of Gloucester","AFKLSSTR","AFKLSSTR"},
  {"of Heristal","AFRSTL","AFRSTL"},
  {"of Hungary","AFNKR","AFNKR"},
  {"of Huntington","AFNTNKTN","AFNTNKTN"},
  {"of Kiev","AFKF","AFKF"},
  {"of Kuno","AFKN","AFKN"},
  {"of Landen","AFLNTN","AFLNTN"},
  {"of Laon","AFLN","AFLN"},
  {"of Leinster","AFLNSTR","AFLNSTR"},
  {"of Lens","AFLNS","AFLNS"},
  {"of Lorraine","AFLRN","AFLRN"},
  {"of Louvain","AFLFN","AFLFN"},
  {"of Mercia","AFMRS","AFMRX"},
  {"of Metz","AFMTS","AFMTS"},
  {"of Meulan","AFMLN","AFMLN"},
  {"of Nass","AFNS","AFNS"},
  {"of Normandy","AFNRMNT","AFNRMNT"},
  {"of Ohningen","AFNNJN","AFNNKN"},
  {"of Orleans","AFRLNS","AFRLNS"},
  {"of Poitou","AFPT","AFPT"},
  {"of Polotzk","AFPLTSK","AFPLTSK"},
  {"of Provence","AFPRFNS","AFPRFNS"},
  {"of Ringelheim","AFRNJLM","AFRNKLM"},
  {"of Salisbury","AFSLSPR","AFSLSPR"},
  {"of Saxony","AFSKSN","AFSKSN"},
  {"of Scotland","AFSKTLNT","AFSKTLNT"},
  {"of Senlis","AFSNLS","AFSNLS"},
  {"of Stafford","AFSTFRT","AFSTFRT"},
  {"of Swabia","AFSP","AFSP"},
  {"of Tongres","AFTNKRS","AFTNKRS"},
  {"of the Tributes","AF0TRPTS","AFTTRPTS"},
  {"unknown","ANKNN","ANKNN"},
  {"van der Gouda","FNTRKT","FNTRKT"},
  {"von Adenbaugh","FNTNP","FNTNP"},
  {"ARCHITure","ARKTR","ARKTR"},
  {"Arnoff","ARNF","ARNF"},
  {"Arnow","ARN","ARNF"},
  {"DANGER","TNJR","TNKR"},
  {"Jankelowicz","JNKLTS","ANKLFX"},
  {"MANGER","MNJR","MNKR"},
  {"McClellan","MKLLN","MKLLN"},
  {"McHugh","MK","MK"},
  {"McLaughlin","MKLFLN","MKLFLN"},
  {"ORCHEStra","ARKSTR","ARKSTR"},
  {"ORCHID","ARKT","ARKT"},
  {"Pierce","PRS","PRS"},
  {"RANGER","RNJR","RNKR"},
  {"Schlesinger","XLSNKR","SLSNJR"},
  {"Uomo","AM","AM"},
  {"Vasserman","FSRMN","FSRMN"},
  {"Wasserman","ASRMN","FSRMN"},
  {"Womo","AM","FM"},
  {"Yankelovich","ANKLFX","ANKLFK"},
  {"accede","AKST","AKST"},
  {"accident","AKSTNT","AKSTNT"},
  {"adelsheim","ATLSM","ATLSM"},
  {"aged","AJT","AKT"},
  {"ageless","AJLS","AKLS"},
  {"agency","AJNS","AKNS"},
  {"aghast","AKST","AKST"},
  {"agio","AJ","AK"},
  {"agrimony","AKRMN","AKRMN"},
  {"album","ALPM","ALPM"},
  {"alcmene","ALKMN","ALKMN"},
  {"alehouse","ALHS","ALHS"},
  {"antique","ANTK","ANTK"},
  {"artois","ART","ARTS"},
  {"automation","ATMXN","ATMXN"},
  {"bacchus","PKS","PKS"},
  {"bacci","PX","PX"},
  {"bajador","PJTR","PHTR"},
  {"bellocchio","PLX","PLX"},
  {"bertucci","PRTX","PRTX"},
  {"biaggi","PJ","PK"},
  {"bough","P","P"},
  {"breaux","PR","PR"},
  {"broughton","PRTN","PRTN"},
  {"cabrillo","KPRL","KPR"},
  {"caesar","SSR","SSR"},
  {"cagney","KKN","KKN"},
  {"campbell","KMPL","KMPL"},
  {"carlisle","KRLL","KRLL"},
  {"carlysle","KRLL","KRLL"},
  {"chemistry","KMSTR","KMSTR"},
  {"chianti","KNT","KNT"},
  {"chorus","KRS","KRS"},
  {"cough","KF","KF"},
  {"czerny","SRN","XRN"},
  {"deffenbacher","TFNPKR","TFNPKR"},
  {"dumb","TM","TM"},
  {"edgar","ATKR","ATKR"},
  {"edge","AJ","AJ"},
  {"filipowicz","FLPTS","FLPFX"},
  {"focaccia","FKX","FKX"},
  {"gallegos","KLKS","KKS"},
  {"gambrelli","KMPRL","KMPRL"},
  {"geithain","K0N","JTN"},
  {"ghiradelli","JRTL","JRTL"},
  {"ghislane","JLN","JLN"},
  {"gough","KF","KF"},
  {"hartheim","HR0M","HRTM"},
  {"heimsheim","HMSM","HMSM"},
  {"hochmeier","HKMR","HKMR"},
  {"hugh","H","H"},
  {"hunger","HNKR","HNJR"},
  {"hungry","HNKR","HNKR"},
  {"island","ALNT","ALNT"},
  {"isle","AL","AL"},
  {"jose","HS","HS"},
  {"laugh","LF","LF"},
  {"mac caffrey","MKFR","MKFR"},
  {"mac gregor","MKRKR","MKRKR"},
  {"pegnitz","PNTS","PKNTS"},
  {"piskowitz","PSKTS","PSKFX"},
  {"queen","KN","KN"},
  {"raspberry","RSPR","RSPR"},
  {"resnais","RSN","RSNS"},
  {"rogier","RJ","RJR"},
  {"rough","RF","RF"},
  {"san jacinto","SNHSNT","SNHSNT"},
  {"schenker","XNKR","SKNKR"},
  {"schermerhorn","XRMRRN","SKRMRRN"},
  {"schmidt","XMT","SMT"},
  {"schneider","XNTR","SNTR"},
  {"school","SKL","SKL"},
  {"schooner","SKNR","SKNR"},
  {"schrozberg","XRSPRK","SRSPRK"},
  {"schulman","XLMN","XLMN"},
  {"schwabach","XPK","XFPK"},
  {"schwarzach","XRSK","XFRTSK"},
  {"smith","SM0","XMT"},
  {"snider","SNTR","XNTR"},
  {"succeed","SKST","SKST"},
  {"sugarcane","XKRKN","SKRKN"},
  {"svobodka","SFPTK","SFPTK"},
  {"tagliaro","TKLR","TLR"},
  {"thames","TMS","TMS"},
  {"theilheim","0LM","TLM"},
  {"thomas","TMS","TMS"},
  {"thumb","0M","TM"},
  {"tichner","TXNR","TKNR"},
  {"tough","TF","TF"},
  {"umbrella","AMPRL","AMPRL"},
  {"vilshofen","FLXFN","FLXFN"},
  {"von schuller","FNXLR","FNXLR"},
  {"wachtler","AKTLR","FKTLR"},
  {"wechsler","AKSLR","FKSLR"},
  {"weikersheim","AKRSM","FKRSM"},
  {"zhao","J","J"}
};

int main()
{
  int matches = 0;
  int mismatches = 0;
  for (auto& test : tests)
  {
    auto result = dm::double_metaphone(test[0]);
    if (result.first != test[1] || result.second != test[2])
    {
      std::clog << "Mismatched " << test[0] << ": " << result.first << " != " << test[1] << " || " << result.second << " != " << test[2] << "\n";
      ++mismatches;
    }
    else
      ++matches;
  }

  std::clog << matches << " matches, " << mismatches << " mismatches.\n";
}
